### ISSUE TITLE
 Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by cscanlin** [eenewbsauce/create-react-app-add-redux#12]
```
cscanlin$ npm i -g create-react-app-add-redux
/Users/cscanlin/.nvm/versions/node/v7.7.1/bin/add-redux -> /Users/cscanlin/.nvm/versions/node/v7.7.1/lib/node_modules/create-react-app-add-redux/index.js
+ create-react-app-add-redux@2.0.0
updated 1 package in 0.855s
cscanlin$ add-redux
/Users/cscanlin/.nvm/versions/node/v7.7.1/lib/node_modules/create-react-app-add-redux/index.js:31
        let depsInstalled = 0;
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
cscanlin$ node -v
v7.7.1
cscanlin$ npm -v
5.6.0
```

**Comment by eenewbsauce** [comment]
Any chance you could bump your node version to LTS?

**Comment by eenewbsauce** [comment]
@cscanlan you could submit a PR to address this issue as well.
